Started logging messages at Thu Sep 11 15:53:12 2014
Info:    Using UV tolerance 1e-006
Info:    Using UV tolerance 1e-006
Info:    HwNlibToTSLib options selected:
Info:        Points: Off
Info:        Curves: On
Info:        Surfaces: Off
Info:        BReps: On
Info:        Create IwAssembly/IwAssemblyInstance objects
Info:        Making untrimmed surfaces into BReps
Info:        Making solids into single BReps
Info:        Make components of failed trims
Info:        Make faces of failed B-reps
Info:    HW SAT v1.2.6-maint
Info:    Reading C:\Users\tpejsa.AD.002\AppData\Local\Autodesk\3dsMax\2012 - 64bit\enu\temp\ImpFile.SAT
Info:    Processing C:\Users\tpejsa.AD.002\AppData\Local\Autodesk\3dsMax\2012 - 64bit\enu\temp\ImpFile.SAT
Info:    Transferring C:\Users\tpejsa.AD.002\AppData\Local\Autodesk\3dsMax\2012 - 64bit\enu\temp\ImpFile.SAT
Info:    
Info:    Found 0 points in file
Info:    Found 0 curves in file
Info:    Found 0 surfaces in file
Info:    Found 0 trimmed surfaces in file
Info:    Found 1 B-reps in file
Info:    Found 24 B-rep faces in file
Info:    
Info:    Using 3D tolerance 1e-006
Info:    Working on 0
Info:        Working on 78
Info:            Created 
Info:        Working on 112
Info:            Created 
Info:        Working on 11
Info:            Created 
Info:        Working on 20
Info:            Created 
Info:        Working on 34
Info:            Created 
Info:        Working on 110
Info:            Created 
Info:        Working on 111
Info:            Created 
Info:        Working on 164
Info:            Created 
Info:        Working on 168
Info:            Created 
Info:        Working on 15
Info:            Created 
Info:        Working on 232
Info:            Created 
Info:        Working on 316
Info:            Created 
Info:        Working on 365
Info:            Created 
Info:        Working on 364
Info:            Created 
Info:        Working on 322
Info:            Created 
Info:        Working on 241
Info:            Created 
Info:        Working on 221
Info:            Created 
Info:        Working on 222
Info:            Created 
Info:        Working on 300
Info:            Created 
Info:        Working on 302
Info:            Created 
Info:        Working on 28
Info:            Created 
Info:        Working on 203
Info:            Created 
Info:        Working on 204
Info:            Created 
Info:        Working on 284
Info:            Created 
Info:        Working on 285
Info:            Created 
Info:        Working on 45
Info:            Created 
Info:        Working on 278
Info:            Created 
Info:        Working on 279
Info:            Created 
Info:        Working on 348
Info:            Created 
Info:        Working on 353
Info:            Created 
Info:        Working on 61
Info:            Created 
Info:        Working on 83
Info:            Created 
Info:        Working on 394
Info:            Created 
Info:        Working on 376
Info:            Created 
Info:        Working on 117
Info:            Created 
Info:        Working on 412
Info:            Created 
Info:        Working on 173
Info:            Created 
Info:        Working on 408
Info:            Created 
Info:        Working on 409
Info:            Created 
Info:        Working on 257
Info:            Created 
Info:        Working on 423
Info:            Created 
Info:        Working on 335
Info:            Created 
Info:        Working on 425
Info:            Created 
Info:        Working on 390
Info:            Created 
Info:        Working on 406
Info:            Created 
Info:        Working on 377
Info:            Created 
Info:        Working on 373
Info:            Created 
Info:        Working on 311
Info:            Created 
Info:        Working on 380
Info:            Created 
Info:        Working on 330
Info:            Created 
Info:        Working on 382
Info:            Created 
Info:        Working on 328
Info:            Created 
Info:        Working on 384
Info:            Created 
Info:        Working on 362
Info:            Created 
Info:        Working on 292
Info:            Created 
Info:        Working on 249
Info:            Created 
Info:        Working on 253
Info:            Created 
Info:        Working on 327
Info:            Created 
Info:        Created 
Info:    Working on BRep 0
Info:        Using 3D tolerance 3.1498e-005
Error:       Unable to create BRep
Info:        In fallback path: Trying to create B-rep face
Info:        Trying model space trim
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 1.77636e-015
Info:        Distance between segments 0
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 1.77636e-015
Info:        Distance between segments 0
Info:        In fallback path: Trying to create B-rep face
Info:        Trying model space trim
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 1.77636e-015
Info:        Distance between segments 0
Info:        In fallback path: Trying to create B-rep face
Info:        Trying model space trim
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 1.77636e-015
Info:        Distance between segments 0
Info:        In fallback path: Trying to create B-rep face
Info:        Trying model space trim
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 7.94411e-015
Info:            Rough distance of curve to surface: 7.94411e-015
Info:            Rough distance of curve to surface: 7.47789e-015
Info:            Rough distance of curve to surface: 3.97205e-015
Info:        Distance between segments 0
Info:        Distance between segments 0
Info:        Distance between segments 0
Info:        Distance between segments 1.77636e-015
Info:        In fallback path: Trying to create B-rep face
Info:        Trying model space trim
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 8.14029e-015
Info:            Rough distance of curve to surface: 7.32411e-015
Info:            Rough distance of curve to surface: 6.7056e-015
Info:            Rough distance of curve to surface: 8.2194e-015
Info:            Rough distance of curve to surface: 8.2194e-015
Info:            Rough distance of curve to surface: 7.94411e-015
Info:            Rough distance of curve to surface: 1.50729e-014
Info:            Rough distance of curve to surface: 1.50729e-014
Info:        Distance between segments 4.44089e-016
Info:        Distance between segments 1.77636e-015
Info:        Distance between segments 0
Info:        Distance between segments 2.22045e-016
Info:        Distance between segments 7.10543e-015
Info:        Distance between segments 0
Info:        Distance between segments 3.55271e-015
Info:        Distance between segments 0
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 1.12347e-014
Info:            Rough distance of curve to surface: 1.12347e-014
Info:            Rough distance of curve to surface: 7.44429e-015
Info:            Rough distance of curve to surface: 5.32907e-015
Info:        Distance between segments 0
Info:        Distance between segments 0
Info:        Distance between segments 4.44089e-016
Info:        Distance between segments 0
Info:        In fallback path: Trying to create B-rep face
Info:        Trying model space trim
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 1.62806e-014
Info:            Rough distance of curve to surface: 1.59022e-014
Info:            Rough distance of curve to surface: 5.64342e-015
Info:            Rough distance of curve to surface: 1.91319e-014
Info:        Distance between segments 7.10543e-015
Info:        Distance between segments 6.66134e-016
Info:        Distance between segments 3.58077e-015
Info:        Distance between segments 3.55271e-015
Info:        In fallback path: Trying to create B-rep face
Info:        Trying model space trim
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 1.44312e-014
Info:            Rough distance of curve to surface: 1.43214e-014
Info:            Rough distance of curve to surface: 1.46482e-014
Info:            Rough distance of curve to surface: 1.50729e-014
Info:        Distance between segments 0
Info:        Distance between segments 0
Info:        Distance between segments 0
Info:        Distance between segments 0
Info:        In fallback path: Trying to create B-rep face
Info:        Trying model space trim
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 5.32914e-015
Info:            Rough distance of curve to surface: 7.94411e-015
Info:            Rough distance of curve to surface: 8.70234e-015
Info:            Rough distance of curve to surface: 8.70234e-015
Info:        Distance between segments 0
Info:        Distance between segments 3.55271e-015
Info:        Distance between segments 0
Info:        Distance between segments 7.10543e-015
Info:        In fallback path: Trying to create B-rep face
Info:        Trying model space trim
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 7.10543e-015
Info:            Rough distance of curve to surface: 1.13742e-014
Info:            Rough distance of curve to surface: 1.13742e-014
Info:            Rough distance of curve to surface: 5.32907e-015
Info:        Distance between segments 0
Info:        Distance between segments 0
Info:        Distance between segments 0
Info:        Distance between segments 8.88178e-016
Info:        In fallback path: Trying to create B-rep face
Info:        Trying model space trim
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 3.58036e-015
Info:            Rough distance of curve to surface: 0
Info:            Rough distance of curve to surface: 3.97205e-015
Info:            Rough distance of curve to surface: 3.97205e-015
Info:        Distance between segments 0
Info:        Distance between segments 0
Info:        Distance between segments 0
Info:        Distance between segments 0
Info:        In fallback path: Trying to create B-rep face
Info:        Trying model space trim
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 4.35117e-015
Info:            Rough distance of curve to surface: 3.97205e-015
Info:            Rough distance of curve to surface: 4.35117e-015
Info:            Rough distance of curve to surface: 4.35117e-015
Info:        Distance between segments 0
Info:        Distance between segments 0
Info:        Distance between segments 0
Info:        Distance between segments 0
Info:        In fallback path: Trying to create B-rep face
Info:        Trying model space trim
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 5.0243e-015
Info:            Rough distance of curve to surface: 5.0243e-015
Info:            Rough distance of curve to surface: 3.97205e-015
Info:            Rough distance of curve to surface: 3.55271e-015
Info:        Distance between segments 0
Info:        Distance between segments 0
Info:        Distance between segments 0
Info:        Distance between segments 0
Info:        In fallback path: Trying to create B-rep face
Info:        Trying model space trim
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 7.94411e-015
Info:            Rough distance of curve to surface: 1.06581e-014
Info:            Rough distance of curve to surface: 1.06581e-014
Info:            Rough distance of curve to surface: 8.70234e-015
Info:        Distance between segments 0
Info:        Distance between segments 0
Info:        Distance between segments 0
Info:        Distance between segments 0
Info:        In fallback path: Trying to create B-rep face
Info:        Trying model space trim
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 5.0243e-015
Info:            Rough distance of curve to surface: 3.55271e-015
Info:            Rough distance of curve to surface: 3.97205e-015
Info:            Rough distance of curve to surface: 3.97205e-015
Info:        Distance between segments 0
Info:        Distance between segments 0
Info:        Distance between segments 0
Info:        Distance between segments 0
Info:        In fallback path: Trying to create B-rep face
Info:        Trying model space trim
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 8.24859e-015
Info:            Rough distance of curve to surface: 8.37906e-015
Info:            Rough distance of curve to surface: 1.46482e-014
Info:            Rough distance of curve to surface: 1.46482e-014
Info:        Distance between segments 0
Info:        Distance between segments 4.44089e-016
Info:        Distance between segments 0
Info:        Distance between segments 0
Info:        In fallback path: Trying to create B-rep face
Info:        Trying model space trim
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 3.57485e-014
Info:            Rough distance of curve to surface: 8.70234e-015
Info:            Rough distance of curve to surface: 3.22202e-014
Info:            Rough distance of curve to surface: 3.58806e-014
Info:        Distance between segments 0
Info:        Distance between segments 0
Info:        Distance between segments 0
Info:        Distance between segments 0
Info:        In fallback path: Trying to create B-rep face
Info:        Trying model space trim
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 8.98115e-015
Info:            Rough distance of curve to surface: 8.70234e-015
Info:            Rough distance of curve to surface: 8.70234e-015
Info:            Rough distance of curve to surface: 1.09862e-014
Info:        Distance between segments 8.88178e-016
Info:        Distance between segments 0
Info:        Distance between segments 0
Info:        Distance between segments 0
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 6.15348e-015
Info:            Rough distance of curve to surface: 7.32411e-015
Info:            Rough distance of curve to surface: 5.32907e-015
Info:            Rough distance of curve to surface: 5.32907e-015
Info:        Distance between segments 0
Info:        Distance between segments 0
Info:        Distance between segments 0
Info:        Distance between segments 0
Info:        In fallback path: Trying to create B-rep face
Info:        Trying model space trim
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 7.10629e-015
Info:            Rough distance of curve to surface: 6.40571e-015
Info:            Rough distance of curve to surface: 3.66205e-015
Info:            Rough distance of curve to surface: 5.34897e-015
Info:        Distance between segments 0
Info:        Distance between segments 0
Info:        Distance between segments 0
Info:        Distance between segments 0
Info:        In fallback path: Trying to create B-rep face
Info:        Trying model space trim
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 5.02414e-015
Info:            Rough distance of curve to surface: 7.32411e-015
Info:            Rough distance of curve to surface: 8.14029e-015
Info:            Rough distance of curve to surface: 8.14029e-015
Info:        Distance between segments 0
Info:        Distance between segments 2.03458e-027
Info:        Distance between segments 0
Info:        Distance between segments 0
Info:        In fallback path: Trying to create B-rep face
Info:        Trying model space trim
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 1.45689e-014
Info:            Rough distance of curve to surface: 1.39557e-014
Info:            Rough distance of curve to surface: 1.25259e-014
Info:            Rough distance of curve to surface: 1.45689e-014
Info:        Distance between segments 0
Info:        Distance between segments 0
Info:        Distance between segments 3.55271e-015
Info:        Distance between segments 4.47403e-016
Info:        In fallback path: Trying to create B-rep face
Info:        Trying model space trim
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 2.24915e-014
Info:            Rough distance of curve to surface: 2.24915e-014
Info:            Rough distance of curve to surface: 7.94411e-015
Info:            Rough distance of curve to surface: 1.06581e-014
Info:        Distance between segments 1.44329e-015
Info:        Distance between segments 0
Info:        Distance between segments 0
Info:        Distance between segments 0
Info:        In fallback path: Trying to create B-rep face
Info:        Trying model space trim
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 7.32411e-015
Info:            Rough distance of curve to surface: 2.14479e-014
Info:            Rough distance of curve to surface: 1.02044e-014
Info:            Rough distance of curve to surface: 1.02044e-014
Info:        Distance between segments 0
Info:        Distance between segments 0
Info:        Distance between segments 4.44089e-016
Info:        Distance between segments 0
Info:        In fallback path: Trying to create B-rep face
Info:        Trying model space trim
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 7.37776e-015
Info:            Rough distance of curve to surface: 7.99361e-015
Info:            Rough distance of curve to surface: 3.66205e-015
Info:            Rough distance of curve to surface: 3.97205e-015
Info:        Distance between segments 0
Info:        Distance between segments 0
Info:        Distance between segments 4.44089e-016
Info:        Distance between segments 0
Info:        In fallback path: Trying to create B-rep face
Info:        Trying model space trim
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 7.11929e-015
Info:            Rough distance of curve to surface: 7.11929e-015
Info:            Rough distance of curve to surface: 7.10543e-015
Info:            Rough distance of curve to surface: 5.0243e-015
Info:            Rough distance of curve to surface: 3.66205e-015
Info:            Rough distance of curve to surface: 3.97205e-015
Info:        Distance between segments 4.44089e-016
Info:        Distance between segments 0
Info:        Distance between segments 0
Info:        Distance between segments 0
Info:        Distance between segments 1.77636e-015
Info:        Distance between segments 0
Info:    Finished with C:\Users\tpejsa.AD.002\AppData\Local\Autodesk\3dsMax\2012 - 64bit\enu\temp\ImpFile.SAT
Info:    Points:                 0 found       0 created       0 failed
Info:    Coordinate Systems      0 found       0 created       0 failed
Info:    Curves:                 0 found       0 created       0 failed
Info:    Surfaces:               0 found       0 created       0 failed
Info:    Trimmed Surfaces:       0 found       0 created       0 failed
Info:    Breps:                  1 found       1 created       0 failed
Finished logging messages at Thu Sep 11 15:53:12 2014
